apiVersion: v1
kind: Service
metadata:
  name: hydra-authn-services
  namespace: iris
spec:
  selector:
    app: hydra-authn-services
  ports:
    - protocol: TCP
      port: 9002
      targetPort: 9002
  type: ClusterIP
