apiVersion: apisix.apache.org/v2
kind: ApisixRoute
metadata:
  name: hydra-authn-route  
  namespace: iris
spec:
  http:
    - name: hydra-authn-route  
      match:
        paths:
          - /hydra-authn-api/* 
      backends:
        - serviceName: hydra-authn-services  
          servicePort: 9002
      plugins:
        - name: limit-count
          enable: true
          config:
            count: 3000
            time_window: 60
            rejected_code: 429
            rejected_msg: "Request limit exceeded. Please try again later."
