apiVersion: apps/v1
kind: Deployment
metadata:
  name: hydra-authn-deployment
  namespace: iris
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hydra-authn-services
  template:
    metadata:
      labels:
        app: hydra-authn-services
        version: "23.12.0"
    spec:
      imagePullSecrets:
        - name: docker-hub-image-secret
      containers:
        - name: hydra-authn-container
          image: {{IMAGE_NAME}}
          ports:
            - containerPort: 9002
          readinessProbe:
            httpGet:
              path: /hydra-authn-api/internal/health
              port: 9002
            initialDelaySeconds: 15
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: /hydra-authn-api/internal/health
              port: 9002
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 10
            successThreshold: 1
            failureThreshold: 10
          resources:
            limits:
              cpu: "1"
              memory: "2Gi" 
            requests:
              cpu: "0.5"
              memory: "256Mi"
          env:
            - name: KAMBALA_GENERATE_OTP_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_GENERATE_OTP_URL
            - name: KAMBALA_AUTHENTICATE_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_AUTHENTICATE_URL
            - name: KAMBALA_OTP_LOGIN_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_OTP_LOGIN_URL
            - name: KAMBALA_LOGOUT_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_LOGOUT_URL
            - name: KAMBALA_FORGOT_PASSWORD_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_FORGOT_PASSWORD_URL
            - name: KAMBALA_CHANGE_PASSWORD_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_CHANGE_PASSWORD_URL
            - name: KAMBALA_GENERATE_SECRET_KEY_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_GENERATE_SECRET_KEY_URL
            - name: KAMBALA_GET_SECRET_KEY_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_GET_SECRET_KEY_URL
            - name: LOGIN_APK_VERSION
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: LOGIN_APK_VERSION
            - name: LOGIN_API_USER
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: LOGIN_API_USER
            - name: LOGIN_SOURCE
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: LOGIN_SOURCE
            - name: LOGIN_FACTOR
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: LOGIN_FACTOR
            - name: LOGIN_VENDOR_CODE
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: LOGIN_VENDOR_CODE
            - name: LOGIN_IMEI
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: LOGIN_IMEI
            - name: KAMBALA_GET_MWLIST_URL
              valueFrom:
                configMapKeyRef:
                  name: hydra-authn-configmap
                  key: KAMBALA_GET_MWLIST_URL      
            - name: HYDRA_AUTHN_API_KEY
              valueFrom:
                secretKeyRef:
                  name: hydra-authn-secret 
                  key: HYDRA_AUTHN_API_KEY
